name: Update gist with random Xcode shortcut
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:    
      - master
jobs:
  update-gist:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        run: |
          chmod +x shortcut.swift
          ./shortcut.swift xcode.json
          git clone https://gist.github.com/{$GIST_TOKEN}.git
          ls -l image.jpg
          git add image.jpg
          git commit -m "Update image"
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
