name: Update gist with random Xcode shortcut
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:    
      - master
jobs:
  update-gist:
    runs-on: macOS-latest
    steps:
    - name: Gist
    - uses: actions/checkout@v2
      with:
        repository: artemnovichkov/c24fd619278b272471af51f06c1ce6b2
    - run: ls
